[tool.isort]
profile = "black"

[tool.pylint]
disable = [
	"missing-class-docstring",
	"missing-function-docstring",
	"missing-module-docstring",
]
recursive = "yes"

[tool.pyright]
typeCheckingMode = "strict"
